// <auto-generated />
using System;
using EDP_Project;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDPProject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EDP_Project.Models.Coupon", b =>
                {
                    b.Property<string>("CouponId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Coupon_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Current_Coupon_Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiry_Date")
                        .HasColumnType("date");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Percentage_Discount")
                        .HasColumnType("int");

                    b.Property<int>("Points_to_redeem")
                        .HasColumnType("int");

                    b.Property<int>("Total_Coupon_Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Total_Coupon_Redeemed")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("EDP_Project.Models.CouponRedemption", b =>
                {
                    b.Property<int>("CouponRedemptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponRedemptionId"));

                    b.Property<string>("CouponId")
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("Date_of_Redemption")
                        .HasColumnType("date");

                    b.HasKey("CouponRedemptionId");

                    b.HasIndex("CouponId");

                    b.ToTable("CouponRedemptions");
                });

            modelBuilder.Entity("EDP_Project.Models.CouponRedemption", b =>
                {
                    b.HasOne("EDP_Project.Models.Coupon", "Coupon")
                        .WithMany("CouponRedemptions")
                        .HasForeignKey("CouponId");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("EDP_Project.Models.Coupon", b =>
                {
                    b.Navigation("CouponRedemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
